name: meinErsterWorkflow

on: 
  push:
    branches:
      - main

jobs:
  changed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Abschied 
        run: echo "Bye Bye"

  zweiter-job:
    runs-on: ubuntu-latest
    needs: changed-job
    steps:
      - name: Datum anzeigen 
        run: date
